Collections:
  - Name: FSDETVIEW
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Batch Size: 8x4
      Architecture:
        - RPN
        - ResNet
    Paper: https://arxiv.org/abs/2007.12107
    README: configs/detection/fsdetview/README.md

Models:
  - Name: fsdetview_r101_c4_8xb4_voc-split3_base-training
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split3/fsdetview_r101_c4_8xb4_voc-split3_base-training.py
    Metadata:
      Training Data: VOC Split3 Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split3
        Metrics:
          base box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split3_1shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split3/fsdetview_r101_c4_8xb4_voc-split3_1shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split3 1shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split3
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split3_2shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split3/fsdetview_r101_c4_8xb4_voc-split3_2shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split3 2shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split3
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split3_3shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split3/fsdetview_r101_c4_8xb4_voc-split3_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split3 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split3
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split3_5shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split3/fsdetview_r101_c4_8xb4_voc-split3_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split3 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split3
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split3_10shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split3/fsdetview_r101_c4_8xb4_voc-split3_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split3 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split3
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
