Collections:
  - Name: FSCE
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - RPN
        - FPN
        - ResNet
    Paper: https://arxiv.org/abs/2003.06957
    README: configs/detection/fsce/README.md

Models:
  - Name: fsce_r101_fpn_voc-split2_base-training
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_voc-split2_base-training.py
    Metadata:
      Training Data: VOC Split2 Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
    Weights: none
  - Name: fsce_r101_fpn_voc-split2_1shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_voc-split2_1shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 1shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_voc-split2_2shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_voc-split2_2shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 2shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_voc-split2_3shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_voc-split2_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_voc-split2_5shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_voc-split2_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_voc-split2_10shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_voc-split2_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_contrastive-loss_voc-split2_3shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_contrastive-loss_voc-split2_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_contrastive-loss_voc-split2_5shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_contrastive-loss_voc-split2_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsce_r101_fpn_contrastive-loss_voc-split2_10shot-fine-tuning
    In Collection: FSCE
    Config: configs/detection/fsce/voc/split2/fsce_r101_fpn_contrastive-loss_voc-split2_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
