Collections:
  - Name: FSDETVIEW
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Batch Size: 8x4
      Architecture:
        - RPN
        - ResNet
    Paper: https://arxiv.org/abs/2007.12107
    README: configs/detection/fsdetview/README.md

Models:
  - Name: fsdetview_r101_c4_8xb4_voc-split2_base-training
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split2/fsdetview_r101_c4_8xb4_voc-split2_base-training.py
    Metadata:
      Training Data: VOC Split2 Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split2_1shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split2/fsdetview_r101_c4_8xb4_voc-split2_1shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 1shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split2_2shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split2/fsdetview_r101_c4_8xb4_voc-split2_2shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 2shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split2_3shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split2/fsdetview_r101_c4_8xb4_voc-split2_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split2_5shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split2/fsdetview_r101_c4_8xb4_voc-split2_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: fsdetview_r101_c4_8xb4_voc-split2_10shot-fine-tuning
    In Collection: FSDETVIEW
    Config: configs/detection/fsdetview/voc/split2/fsdetview_r101_c4_8xb4_voc-split2_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
