Collections:
  - Name: Attention RPN
    Metadata:
      Training Data: VOC Split1
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - Attention RPN
        - ResNet
    Paper: https://arxiv.org/abs/1908.01998
    README: configs/detection/attention_rpn/README.md

Models:
  - Name: attention_rpn_r50_c4_voc-split1_base-training
    In Collection: Attention RPN
    Config: configs/detection/attention_rpn/coco/attention-rpn_r50_c4_voc-split1_base-training.py
    Metadata:
      Training Data: VOC Split1 Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC
        Metrics:
          base box AP50: none
    Weights: none
  - Name: attention_rpn_r50_c4_voc-split1_1shot-fine-tuning
    In Collection: Attention RPN
    Config: configs/detection/attention_rpn/coco/attention-rpn_r50_c4_voc-split1_1shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 1shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC
        Metrics:
          novel box AP50: none
    Weights: none
  - Name: attention_rpn_r50_c4_voc-split1_2shot-fine-tuning
    In Collection: Attention RPN
    Config: configs/detection/attention_rpn/coco/attention-rpn_r50_c4_voc-split1_2shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 2shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC
        Metrics:
          novel box AP50: none
    Weights: none
  - Name: attention_rpn_r50_c4_voc-split1_3shot-fine-tuning
    In Collection: Attention RPN
    Config: configs/detection/attention_rpn/coco/attention-rpn_r50_c4_voc-split1_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC
        Metrics:
          novel box AP50: none
    Weights: none
  - Name: attention_rpn_r50_c4_voc-split1_5shot-fine-tuning
    In Collection: Attention RPN
    Config: configs/detection/attention_rpn/coco/attention-rpn_r50_c4_voc-split1_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC
        Metrics:
          novel box AP50: none
    Weights: none
  - Name: attention_rpn_r50_c4_voc-split1_10shot-fine-tuning
    In Collection: Attention RPN
    Config: configs/detection/attention_rpn/coco/attention-rpn_r50_c4_voc-split1_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC
        Metrics:
          novel box AP50: none
    Weights: none
