Collections:
  - Name: MPSR
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 2x V100 GPUs
      Batch Size: 2x2
      Architecture:
        - RPN
        - FPN
        - ResNet
    Paper: https://arxiv.org/abs/2007.09384
    README: configs/detection/mpsr/README.md

Models:
  - Name: mpsr_r101_fpn_2xb2_voc-split1_base-training
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_base-training.py
    Metadata:
      Training Data: VOC Split1 Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split1
        Metrics:
          base box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split1_1shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_1shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 1shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split1
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split1_2shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_2shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 2shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split1
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split1_3shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split1
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split1_5shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split1
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split1_10shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split1 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split1
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
