Collections:
  - Name: MPSR
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 2x V100 GPUs
      Batch Size: 2x2
      Architecture:
        - RPN
        - FPN
        - ResNet
    Paper: https://arxiv.org/abs/2007.09384
    README: configs/detection/mpsr/README.md

Models:
  - Name: mpsr_r101_fpn_2xb2_voc-split2_base-training
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split2/mpsr_r101_fpn_2xb2_voc-split2_base-training.py
    Metadata:
      Training Data: VOC Split2 Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split2_1shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split2/mpsr_r101_fpn_2xb2_voc-split2_1shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 1shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split2_2shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split2/mpsr_r101_fpn_2xb2_voc-split2_2shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 2shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split2_3shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split2/mpsr_r101_fpn_2xb2_voc-split2_3shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 3shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split2_5shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split2/mpsr_r101_fpn_2xb2_voc-split2_5shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 5shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: mpsr_r101_fpn_2xb2_voc-split2_10shot-fine-tuning
    In Collection: MPSR
    Config: configs/detection/mpsr/voc/split2/mpsr_r101_fpn_2xb2_voc-split2_10shot-fine-tuning.py
    Metadata:
      Training Data: VOC Split2 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: VOC Split2
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
