Collections:
  - Name: Meta RCNN
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Batch Size: 8x4
      Architecture:
        - RPN
        - ResNet
    Paper: https://arxiv.org/abs/1909.13032
    README: configs/detection/meta_rcnn/README.md

Models:
  - Name: meta-rcnn_r50_c4_8xb4_coco_base-training
    In Collection: Meta RCNN
    Config: configs/detection/meta_rcnn/coco/meta-rcnn_r50_c4_8xb4_coco_base-training.py
    Metadata:
      Training Data: COCO Base Classes
    Results:
      - Task: Few Shot Object Detection
        Dataset: COCO
        Metrics:
          base box AP: none
    Weights: none
  - Name: meta-rcnn_r50_c4_8xb4_coco_10shot-fine-tuning
    In Collection: Meta RCNN
    Config: configs/detection/meta_rcnn/coco/meta-rcnn_r50_c4_8xb4_coco_10shot-fine-tuning.py
    Metadata:
      Training Data: COCO 10shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: COCO
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
  - Name: meta-rcnn_r50_c4_8xb4_coco_30shot-fine-tuning
    In Collection: Meta RCNN
    Config: configs/detection/meta_rcnn/coco/meta-rcnn_r50_c4_8xb4_coco_30shot-fine-tuning.py
    Metadata:
      Training Data: COCO 30shot
    Results:
      - Task: Few Shot Object Detection
        Dataset: COCO
        Metrics:
          base box AP: none
          novel box AP: none
    Weights: none
